import * as yup from "yup";

export const WORKFLOW_DETAIL = {
  taskInstanceId: "-5758677146684975299",
  workflowInstanceId: "-4131850724901259223",
  addedOn: "2024-11-21T09:30:28.251+00:00",
  addedBy: "7865233876899068603",
  savedOn: null,
  savedBy: "0",
  committedOn: null,
  committedBy: "0",
  statusInId: "3991732228477460336",
  statusOutId: "0",
  tenantId: "-3733423605126616143",
  nextTenantId: "0",
  nextTaskTypeId: "0",
  taskTypeId: "-4903110845343936826",
  data: [
    988325, 0, 0, 0, 988322, 988320, 0, 988321, 988324, 988323, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  ],
  note: null,
  renderingStyle: "Wizard",
  selectedTaskStatus: {
    tokenId: 0,
    id: "0",
    i18nName: "",
    startingTask: false,
    endingTask: false,
  },
  businessErrorMessage: null,
  statuses: {
    "1": {
      tokenId: 988326,
      id: "-2837313266323908774",
      i18nName: "Submit",
      startingTask: true,
      endingTask: false,
    },
  },
  variables: {
    "33": {
      id: "33",
      tokenId: 0,
      i18nName: "resend_button",
      type: 8,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "OTP Verification",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "-6046217324609910648",
      exitClassDataId: "988327",
      instanceId: "9877",
      textValue: null,
      numericValue: "0",
      displayOrder: 130,
      variableStyle: '{bgColor: "#1F1F1F"}',
    },
    "22": {
      id: "22",
      tokenId: 0,
      i18nName: "intro_label",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue:
        "Get an instant micro-finance, starting from SAR 2,000! No paper work, fast approvals and flexible terms",
      numericValue: "0",
      displayOrder: 20,
      variableStyle:
        '{htmlLabel: `<h2 style="font-family: Inter; font-weight: 400; font-size: 16px; line-height: 23px; color:#1F1F1F">Get an instant micro-finance, starting from <b>SAR 2,000!</b> No paper work, fast approvals and flexible terms</h2>`,}',
    },
    "34": {
      id: "34",
      tokenId: 0,
      i18nName: "user_name",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "User Enrollment",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9878",
      textValue: null,
      numericValue: "0",
      displayOrder: 140,
      variableStyle: null,
    },
    "23": {
      id: "23",
      tokenId: 0,
      i18nName: "national_id_iqama_text",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9867",
      textValue: null,
      numericValue: "0",
      displayOrder: 30,
      variableStyle: `{startIcon: "ID.svg",}`,
    },
    "35": {
      id: "35",
      tokenId: 0,
      i18nName: "name",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "User Enrollment",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9879",
      textValue: null,
      numericValue: "0",
      displayOrder: 150,
      variableStyle: null,
    },
    "24": {
      id: "24",
      tokenId: 0,
      i18nName: "saudi_mobile_number_text",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9868",
      textValue: null,
      numericValue: "0",
      displayOrder: 40,
      variableStyle: '{startIcon: "SmartPhone.svg",}',
    },
    "36": {
      id: "36",
      tokenId: 0,
      i18nName: "email",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "User Enrollment",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9880",
      textValue: null,
      numericValue: "0",
      displayOrder: 160,
      variableStyle: null,
    },
    "25": {
      id: "25",
      tokenId: 0,
      i18nName: "are_you_a_bab_customer_tick",
      type: 9,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 16,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9869",
      textValue: null,
      numericValue: "0",
      displayOrder: 50,
      variableStyle: null,
    },
    "37": {
      id: "37",
      tokenId: 0,
      i18nName: "password",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "User Enrollment",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9881",
      textValue: null,
      numericValue: "0",
      displayOrder: 170,
      variableStyle: null,
    },
    "26": {
      id: "26",
      tokenId: 0,
      i18nName: "t_an_c_tick",
      type: 9,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 16,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9870",
      textValue: null,
      numericValue: "0",
      displayOrder: 60,
      variableStyle:
        '{htmlLabel: `<div>I have read the <a href="/t" target="_blank" style="color:#C65600">terms & conditions</a></div>`,}',
    },
    "38": {
      id: "38",
      tokenId: 0,
      i18nName: "confirm_password",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "User Enrollment",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9882",
      textValue: null,
      numericValue: "0",
      displayOrder: 180,
      variableStyle: null,
    },
    "27": {
      id: "27",
      tokenId: 0,
      i18nName: "marketing_tick",
      type: 9,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 16,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9871",
      textValue: null,
      numericValue: "0",
      displayOrder: 70,
      variableStyle: null,
    },
    "39": {
      id: "39",
      tokenId: 0,
      i18nName: "register_button",
      type: 8,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "User Enrollment",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "7534973078801056999",
      exitClassDataId: "988328",
      instanceId: "9883",
      textValue: null,
      numericValue: "0",
      displayOrder: 190,
      variableStyle: '{bgColor: "#1F1F1F", isValidateBeforeClick: 1,}',
    },
    "28": {
      id: "28",
      tokenId: 0,
      i18nName: "button_go_next",
      type: 8,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "-1729976961630728888",
      exitClassDataId: "988329",
      instanceId: "9872",
      textValue: null,
      numericValue: "0",
      displayOrder: 80,
      variableStyle:
        '{bgColor: "#1F1F1F",endIcon: "RightBtnArrow.svg", size: "large", isValidateBeforeClick: 1, borderRadius: "16px"}',
    },
    "29": {
      id: "29",
      tokenId: 0,
      i18nName: "label_title",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "OTP Verification",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9873",
      textValue: "A code was sent to your mobile number",
      numericValue: "0",
      displayOrder: 90,
      variableStyle:
        '{htmlLabel: `<div style="color:white; font-family: inter; font-weight:700;  font-size: 24px; line-height:31px; text-align: center;">A code was sent to your mobile number</div>`,}',
    },
    "30": {
      id: "30",
      tokenId: 0,
      i18nName: "label_sub_title",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "OTP Verification",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9874",
      textValue: "Please enter the code you received",
      numericValue: "0",
      displayOrder: 100,
      variableStyle:
        '{htmlLabel: `<div style="font-family: Inter; font-size: 16px; font-weight: 400;line-height: 23px;text-align: center; color: white; ">Please enter the code you received</div>`,}',
    },
    "31": {
      id: "31",
      tokenId: 0,
      i18nName: "otp",
      type: 2,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "OTP Verification",
      mimeType: null,
      jdbcType: 4,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9875",
      textValue: null,
      numericValue: "0",
      displayOrder: 110,
      variableStyle: "{otpCount: 4,}",
    },
    "32": {
      id: "32",
      tokenId: 0,
      i18nName: "label_desc",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "OTP Verification",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9876",
      textValue: "If you don`t receive the mumber in 1:00 minute, click here",
      numericValue: "0",
      displayOrder: 120,
      variableStyle:
        '{htmlLabel: `<div style="font-family: Inter; font-size: 16px; font-weight: 400;line-height: 23px;text-align: center; color: white; ">Please enter the code you received</div>`,}',
    },
    "21": {
      id: "21",
      tokenId: 0,
      i18nName: "title_label",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9865",
      textValue: "Need more funds over your current financing?",
      numericValue: "0",
      displayOrder: 10,
      variableStyle:
        '{htmlLabel: `<h1 style="font-family: Inter; font-weight: 700; font-size: 36px; line-height: 36px; color:#1F1F1F">Need <span style="color: #BD0000">more funds</span> over your current financing?</h1>`,}',
    },
    "41": {
      id: "41",
      tokenId: 0,
      i18nName: "hello_user",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Products",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9865",
      textValue: "Hello Mansour,",
      numericValue: "0",
      displayOrder: 200,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 700; font-size: 32px; line-height: 35px; padding-bottom: 4px;"> Hello Mansour, </p>',
      }`,
    },
    "42": {
      id: "42",
      tokenId: 0,
      i18nName: "salary_label",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Products",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "SalaryLabel",
      numericValue: "0",
      displayOrder: 210,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size:12px; line-height: 15px; color: #C65600;"> Your salary is: </p>',
      }`,
    },
    "43": {
      id: "43",
      tokenId: 0,
      i18nName: "salary",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Products",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Salary",
      numericValue: "0",
      displayOrder: 220,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 600; font-size: 18px; line-height: 22px; margin-top: -10px"> 20,000 SAR </p>',
      }`,
    },
    "44": {
      id: "44",
      tokenId: 0,
      i18nName: "eligible_for_loan",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Products",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Your'e eligible for a loan!",
      numericValue: "0",
      displayOrder: 230,
      variableStyle: `{
        htmlLabel: '<div style="padding: 12px 24px;  margin-bottom: 10px; display: flex; background-color: #FFE3B0; border-radius: 36px; justify-content: center; align-items: center; gap: 10px;"> <img src="/images/Check.svg" alt="" /> <p style="color: #6E4C00; font-weight: 600; font-size: 14px; line-height: 14px;">You are eligible for a loan!</p></div>'
      }`,
    },
    "45": {
      id: "45",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Products",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Choose your product",
      numericValue: "0",
      displayOrder: 240,
      variableStyle: `{
        htmlLabel:
          '<p style="font-weight: 600; font-size: 18px; line-height: 22px;">Choose your product</p>',
      }`,
    },
    "46": {
      id: "46",
      tokenId: 0,
      i18nName: "loan_calculator",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Products",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: null,
      numericValue: "0",
      displayOrder: 250,
      variableStyle: `{
        htmlLabel:
          '<p style="color: #C65600; font-weight: 600; font-size: 14px; line-height: 15px; display: flex; gap: 5px; align-items: center; cursor: pointer; max-width: fit-content;"><img src="/images/Calculator.svg" alt="" /><span>Loan calculator</span></p>',
      }`,
    },
    "47": {
      id: "47",
      tokenId: 0,
      i18nName: "Personal loan",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Products",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Personal Loan",
      numericValue: "0",
      displayOrder: 260,
      variableStyle:
        "{ bgColor: 'white', color: 'black', fontWeight: '600', justifyContent: 'start', startIcon: 'PersonalLoan.svg', size: 'large', height: '56px', borderRadius: '8px' }",
    },
    "48": {
      id: "48",
      tokenId: 0,
      i18nName: "Re-Financing",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Products",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Re-Financing",
      numericValue: "0",
      displayOrder: 270,
      variableStyle:
        "{ bgColor: 'white', color: 'black', fontWeight: '600', justifyContent: 'start', startIcon: 'ReFinancing.svg', size: 'large', height: '56px', borderRadius: '8px' }",
    },
    "49": {
      id: "49",
      tokenId: 0,
      i18nName: "Auto-Loan",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Products",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Auto-Loan",
      numericValue: "0",
      displayOrder: 280,
      variableStyle:
        "{ bgColor: 'white', color: 'black', fontWeight: '600', justifyContent: 'start', startIcon: 'AutoLoan.svg', size: 'large', height: '56px', borderRadius: '8px' }",
    },
    "50": {
      id: "50",
      tokenId: 0,
      i18nName: "Retail Finance",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Products",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Retail Finance",
      numericValue: "0",
      displayOrder: 290,
      variableStyle:
        "{ bgColor: 'white', color:'black', fontWeight: '600', justifyContent: 'start', startIcon: 'RetailFinance.svg', size: 'large', height: '56px', borderRadius: '8px' }",
    },
    "51": {
      id: "51",
      tokenId: 0,
      i18nName: "Continue",
      type: 8,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Products",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "-1729976961630728888",
      exitClassDataId: "988329",
      instanceId: "9872",
      textValue: null,
      numericValue: "0",
      displayOrder: 300,
      variableStyle:
        '{bgColor: "#1F1F1F",endIcon: "RightBtnArrow.svg", size: "large", isValidateBeforeClick: 1, borderRadius: "16px"}',
    },
    "52": {
      id: "52",
      tokenId: 0,
      i18nName: "hello_user",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9865",
      textValue: "Hello Mansour,",
      numericValue: "0",
      displayOrder: 301,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 700; font-size: 32px; line-height: 35px; padding-bottom: 4px;"> Hello Mansour, </p>',
      }`,
    },
    "53": {
      id: "53",
      tokenId: 0,
      i18nName: "eligible_for_loan",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Your'e eligible for a loan!",
      numericValue: "0",
      displayOrder: 302,
      variableStyle: `{
        htmlLabel: '<div style="padding: 12px 24px;  margin-bottom: 12px; display: flex; background-color: #FFE3B0; border-radius: 36px; justify-content: center; align-items: center; gap: 10px;"> <img src="/images/Check.svg" alt="" /> <p style="color: #6E4C00; font-weight: 600; font-size: 14px; line-height: 14px;">You are applying for a Personal Loan</p></div>'
      }`,
    },
    "54": {
      id: "54",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Responsible Lending",
      numericValue: "0",
      displayOrder: 303,
      variableStyle: `{
        htmlLabel:
          '<p style="font-weight: 600; font-size: 18px; line-height: 22px;">Responsible lending</p>',
      }`,
    },
    "55": {
      id: "55",
      tokenId: 0,
      i18nName: "loan_calculator",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: null,
      numericValue: "0",
      displayOrder: 304,
      variableStyle: `{
        htmlLabel:
          '<p style="color: #C65600; font-weight: 500; font-size: 12px; line-height: 15px; display: flex; gap: 5px; align-items: center; cursor: pointer; max-width: fit-content;"><span>Expenses: 6000 SAR</span></p>',
      }`,
    },
    "56": {
      id: "56",
      tokenId: 0,
      i18nName: "Number of dependents",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9868",
      textValue: null,
      numericValue: "0",
      displayOrder: 350,
      variableStyle: '{startIcon: "NumberOfDependents.svg",}',
    },
    "57": {
      id: "57",
      tokenId: 0,
      i18nName: "Food expenses",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9868",
      textValue: null,
      numericValue: "0",
      displayOrder: 360,
      variableStyle: '{startIcon: "FoodExpenses.svg", endIcon: "SAR.svg"}',
    },
    "58": {
      id: "58",
      tokenId: 0,
      i18nName: "Education expenses",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9868",
      textValue: null,
      numericValue: "0",
      displayOrder: 370,
      variableStyle: '{startIcon: "EducationExpenses.svg", endIcon: "SAR.svg"}',
    },
    "59": {
      id: "59",
      tokenId: 0,
      i18nName: "Healthcare expenses",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9868",
      textValue: null,
      numericValue: "0",
      displayOrder: 380,
      variableStyle:
        '{startIcon: "HealthcareExpenses.svg", endIcon: "SAR.svg"}',
    },
    "60": {
      id: "60",
      tokenId: 0,
      i18nName: "Insurance expenses",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9868",
      textValue: null,
      numericValue: "0",
      displayOrder: 400,
      variableStyle: '{startIcon: "InsuranceExpenses.svg", endIcon: "SAR.svg"}',
    },
    "61": {
      id: "61",
      tokenId: 0,
      i18nName: "Housing (rent) and services",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9868",
      textValue: null,
      numericValue: "0",
      displayOrder: 410,
      variableStyle:
        '{startIcon: "HousingAndServices.svg", endIcon: "SAR.svg"}',
    },
    "62": {
      id: "63",
      tokenId: 0,
      i18nName: "Domestic worker wages",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9868",
      textValue: null,
      numericValue: "0",
      displayOrder: 420,
      variableStyle:
        '{startIcon: "DomesticWorkerWages.svg", endIcon: "SAR.svg"}',
    },
    "64": {
      id: "64",
      tokenId: 0,
      i18nName: "Transportation & communication",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9868",
      textValue: null,
      numericValue: "0",
      displayOrder: 430,
      variableStyle: '{startIcon: "Transportation.svg", endIcon: "SAR.svg"}',
    },
    "65": {
      id: "65",
      tokenId: 0,
      i18nName: "Other expenses",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9868",
      textValue: null,
      numericValue: "0",
      displayOrder: 440,
      variableStyle: '{startIcon: "OtherExpenses.svg", endIcon: "SAR.svg"}',
    },
    "66": {
      id: "66",
      tokenId: 0,
      i18nName: "Continue",
      type: 8,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Responsible Lending",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "-1729976961630728888",
      exitClassDataId: "988329",
      instanceId: "9872",
      textValue: null,
      numericValue: "0",
      displayOrder: 440,
      variableStyle:
        '{bgColor: "#1F1F1F",endIcon: "RightBtnArrow.svg", size: "large", isValidateBeforeClick: 1, borderRadius: "16px"}',
    },
    "67": {
      id: "67",
      tokenId: 0,
      i18nName: "Congrats_user",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9865",
      textValue: "Hello Mansour,",
      numericValue: "0",
      displayOrder: 450,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 700; font-size: 32px; line-height: 35px; padding-bottom: 4px;"> Congrats Mansour, </p>',
      }`,
    },
    "68": {
      id: "68",
      tokenId: 0,
      i18nName: "salary_label",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "SalaryLabel",
      numericValue: "0",
      displayOrder: 460,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size:12px; line-height: 15px; color: #C65600;"> Your salary is: </p>',
      }`,
    },
    "69": {
      id: "69",
      tokenId: 0,
      i18nName: "salary",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Salary",
      numericValue: "0",
      displayOrder: 461,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 600; font-size: 18px; line-height: 22px; margin-top: -10px;"> 20,000 SAR </p>',
      }`,
    },
    "70": {
      id: "70",
      tokenId: 0,
      i18nName: "salary_label",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "SalaryLabel",
      numericValue: "0",
      displayOrder: 462,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size:12px; line-height: 15px; color: #C65600;"> Expanses: </p>',
      }`,
    },
    "71": {
      id: "71",
      tokenId: 0,
      i18nName: "salary",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Salary",
      numericValue: "0",
      displayOrder: 463,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 600; font-size: 18px; line-height: 22px; padding-bottom: 16px; margin-top: -10px;"> 6,000 SAR </p>',
      }`,
    },
    "72": {
      id: "72",
      tokenId: 0,
      i18nName: "salary",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Salary",
      numericValue: "0",
      displayOrder: 463,
      variableStyle: `{
        htmlLabel: '<div style="padding: 12px 24px; display: flex; background-color: #3D2000; border-radius: 22px; justify-content: center; align-items: center; gap: 10px;"><img src="/images/Celebration.svg" alt="" /><div><p style="color: #F19D00; font-weight: 400; font-size: 12px; line-height: 18px;">You are eligible for a personal loan up to</p><p style="color: white; font-weight: 700; font-size: 20px; line-height: 22px;"> 40,000 SAR</p></div></div>'
      }`,
    },
    "73": {
      id: "73",
      tokenId: 0,
      i18nName: "",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Responsible Lending",
      numericValue: "0",
      displayOrder: 464,
      variableStyle: `{
        htmlLabel:
          '<p style="font-weight: 600; font-size: 18px; line-height: 22px;">Tailor your Personal Loan</p>',
      }`,
    },
    "77": {
      id: "77",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "",
      numericValue: "0",
      displayOrder: 475,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size: 16px; color: #6B5121;">Total Amount</p>'
      }`,
    },
    "78": {
      id: "78",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "",
      numericValue: "0",
      displayOrder: 480,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size: 16px; margin-top: -12px">40,000 SAR</p>'
      }`,
    },
    "79": {
      id: "79",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "",
      numericValue: "0",
      displayOrder: 485,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size: 16px; color: #6B5121;">Monthly Payment</p>'
      }`,
    },
    "80": {
      id: "80",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Responsible Lending",
      numericValue: "0",
      displayOrder: 490,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size: 16px; margin-top: -12px">1,667 SAR</p>'
      }`,
    },
    "81": {
      id: "81",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "",
      numericValue: "0",
      displayOrder: 495,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size: 16px; color: #6B5121;">Loan Tenor</p>'
      }`,
    },
    "82": {
      id: "82",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "",
      numericValue: "0",
      displayOrder: 500,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size: 16px; margin-top: -12px">24 Months</p>'
      }`,
    },
    "83": {
      id: "83",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Responsible Lending",
      numericValue: "0",
      displayOrder: 505,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size: 16px; color: #6B5121;">First Installment</p>'
      }`,
    },
    "84": {
      id: "84",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Responsible Lending",
      numericValue: "0",
      displayOrder: 510,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size: 16px; margin-top: -12px">01/08/2024</p>'
      }`,
    },
    "85": {
      id: "85",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Responsible Lending",
      numericValue: "0",
      displayOrder: 515,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size: 16px; color: #6B5121;">Last Installment</p>'
      }`,
    },
    "86": {
      id: "86",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Responsible Lending",
      numericValue: "0",
      displayOrder: 520,
      variableStyle: `{
        htmlLabel: '<p style="font-weight: 400; font-size: 16px; margin-top: -12px">01/08/2026</p>'
      }`,
    },

    "87": {
      id: "87",
      tokenId: 0,
      i18nName: "choose_your_product",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9866",
      textValue: "Responsible Lending",
      numericValue: "0",
      displayOrder: 525,
      variableStyle: `{
        htmlLabel: '<div style="display: flex; justify-content: space-between;"><p style="font-weight: 400; font-size: 16px; color: #6B5121;">Last Installment</p><p style="font-weight: 400; font-size: 16px;">01/80/2026</p></div>'
      }`,
    },
    "88": {
      id: "88",
      tokenId: 0,
      i18nName: "Review",
      type: 8,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Tailor Loan",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "-1729976961630728888",
      exitClassDataId: "988329",
      instanceId: "9872",
      textValue: null,
      numericValue: "0",
      displayOrder: 530,
      variableStyle:
        '{bgColor: "#1F1F1F",endIcon: "RightBtnArrow.svg", size: "large", isValidateBeforeClick: 1, borderRadius: "16px"}',
    },
  },
  variablesByName: {
    label_sub_title: "30",
    resend_button: "33",
    saudi_mobile_number_text: "24",
    t_an_c_tick: "26",
    label_title: "29",
    user_name: "34",
    marketing_tick: "27",
    otp: "31",
    register_button: "39",
    confirm_password: "38",
    button_go_next: "28",
    intro_label: "22",
    password: "37",
    are_you_a_bab_customer_tick: "25",
    name: "35",
    label_desc: "32",
    email: "36",
    national_id_iqama_text: "23",
    title_label: "21",
  },
};

export { yup };

export const JDBC_TYPE = {
  Button: -7,
  UploadDocument: -2,
  DecimalInput: 3,
  IntegerInput: 4,
  TextInput: 12,
  TextAreaInput: 2005,
  Checkbox: 16,
  URL: 70,
  DatePicker: 91,
  TimePicker: 92,
  Label: 93,
};

export const FORM_TYPE = {
  TAB: "Tab",
  WIZARD: "Wizard",
};

export const CONST_WORDS = {
  sessionTaskDetail: "CME_TASK_DETAIL",
};

export const ALLOWED_FILE_EXTENSION = ["pdf", "jpg", "png", "jpeg", "gif"];
