import * as yup from "yup";

export const WORKFLOW_DETAIL = {
  taskInstanceId: "2532956471760631616",
  workflowInstanceId: "5337994628980465355",
  addedOn: "2024-12-05T07:08:19.860+00:00",
  addedBy: "-1257832776003350768",
  savedOn: null,
  savedBy: "0",
  committedOn: null,
  committedBy: "0",
  statusInId: "7419865565527950826",
  statusOutId: "0",
  tenantId: "7958465429197662055",
  nextTenantId: "0",
  nextTaskTypeId: "0",
  taskTypeId: "3007593960759313752",
  data: [
    1161957, 0, 0, 0, 1161954, 1161952, 0, 1161953, 1161956, 1161955, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  ],
  note: null,
  renderingStyle: "Wizard",
  selectedTaskStatus: {
    tokenId: 0,
    id: "0",
    i18nName: "",
    startingTask: false,
    endingTask: false,
  },
  businessErrorMessage: null,
  statuses: {
    "1": {
      tokenId: 1161958,
      id: "-1993477253873990763",
      i18nName: "Submit",
      startingTask: true,
      endingTask: false,
    },
  },
  variables: {
    "286": {
      id: "286",
      tokenId: 0,
      i18nName: "loan_principal_min",
      type: 2,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Loan Simulation",
      mimeType: null,
      jdbcType: 4,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "11167",
      textValue: null,
      numericValue: "0",
      displayOrder: 10,
      variableStyle: null,
    },
    "287": {
      id: "287",
      tokenId: 0,
      i18nName: "loan_principal_max",
      type: 2,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Loan Simulation",
      mimeType: null,
      jdbcType: 4,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "11168",
      textValue: null,
      numericValue: "0",
      displayOrder: 20,
      variableStyle: null,
    },
    "288": {
      id: "288",
      tokenId: 0,
      i18nName: "loan_principal",
      type: 2,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Loan Simulation",
      mimeType: null,
      jdbcType: 4,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "11169",
      textValue: null,
      numericValue: "0",
      displayOrder: 30,
      variableStyle: null,
    },
    "289": {
      id: "289",
      tokenId: 0,
      i18nName: "loan_tenure_min",
      type: 2,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Loan Simulation",
      mimeType: null,
      jdbcType: 4,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "11170",
      textValue: null,
      numericValue: "0",
      displayOrder: 40,
      variableStyle: null,
    },
    "290": {
      id: "290",
      tokenId: 0,
      i18nName: "loan_tenure_max",
      type: 2,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Loan Simulation",
      mimeType: null,
      jdbcType: 4,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "11171",
      textValue: null,
      numericValue: "0",
      displayOrder: 50,
      variableStyle: null,
    },
    "291": {
      id: "291",
      tokenId: 0,
      i18nName: "loan_tenure",
      type: 2,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Loan Simulation",
      mimeType: null,
      jdbcType: 4,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "11172",
      textValue: null,
      numericValue: "0",
      displayOrder: 60,
      variableStyle: null,
    },
    "292": {
      id: "292",
      tokenId: 0,
      i18nName: "simulation_button",
      type: 8,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Loan Simulation",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "-3044251226266823500",
      exitClassDataId: "1161959",
      instanceId: "11173",
      textValue: null,
      numericValue: "0",
      displayOrder: 70,
      variableStyle: null,
    },
    "293": {
      id: "293",
      tokenId: 0,
      i18nName: "monthly_payment",
      type: 2,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Loan Simulation",
      mimeType: null,
      jdbcType: 4,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "11174",
      textValue: null,
      numericValue: "0",
      displayOrder: 80,
      variableStyle: null,
    },
    "312": {
      id: "312",
      tokenId: 0,
      i18nName: "first_installment_date",
      type: 3,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Loan Simulation",
      mimeType: null,
      jdbcType: 91,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "11175",
      textValue: null,
      numericValue: "0",
      displayOrder: 90,
      variableStyle: null,
    },
    "313": {
      id: "313",
      tokenId: 0,
      i18nName: "last_installment_date",
      type: 3,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Loan Simulation",
      mimeType: null,
      jdbcType: 91,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "11176",
      textValue: null,
      numericValue: "0",
      displayOrder: 100,
      variableStyle: null,
    },
    "315": {
      id: "315",
      tokenId: 0,
      i18nName: "apply_for_loan_button",
      type: 8,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Loan Simulation",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "-6981095236057456383",
      exitClassDataId: "1161961",
      instanceId: "11177",
      textValue: null,
      numericValue: "0",
      displayOrder: 110,
      variableStyle: null,
    },
    "316": {
      id: "316",
      tokenId: 0,
      i18nName: "list_of_loan_products",
      type: 2,
      comboListName: "business.loan_products",
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Loan Products",
      mimeType: null,
      jdbcType: 4,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "11166",
      textValue: null,
      numericValue: "0",
      displayOrder: 10,
      variableStyle: null,
    },
  },
  variablesByName: {
    saudi_mobile_number_text: "302",
    t_an_c_tick: "304",
    t_and_c_text: "306",
    loan_tenure_max: "290",
    simulation_button: "292",
    list_of_loan_products: "316",
    first_installment_date: "312",
    marketing_tick: "305",
    otp: "284",
    loan_principal: "288",
    loan_principal_max: "287",
    send_otp_button: "314",
    confirm_password: "283",
    apply_for_loan_button: "315",
    last_installment_date: "313",
    password: "282",
    loan_tenure_min: "289",
    loan_principal_min: "286",
    loan_tenure: "291",
    username: "281",
    monthly_payment: "293",
    national_id_iqama_text: "301",
  },
};

export { yup };

export const JDBC_TYPE = {
  Button: -7,
  UploadDocument: -2,
  DecimalInput: 3,
  IntegerInput: 4,
  TextInput: 12,
  TextAreaInput: 2005,
  Checkbox: 16,
  URL: 70,
  DatePicker: 91,
  TimePicker: 92,
  Label: 93,
  Password: 2012,
};

export const FORM_TYPE = {
  TAB: "Tab",
  WIZARD: "Wizard",
};

export const CONST_WORDS = {
  sessionTaskDetail: "CME_TASK_DETAIL",
  token: "CME_TOKEN",
  username: "CME_USERNAME",
  lastActivePage: "CME_LAST_ACTIVE_PAGE",
};

export const ALLOWED_FILE_EXTENSION = ["pdf", "jpg", "png", "jpeg", "gif"];
