import * as yup from "yup";

export const WORKFLOW_DETAIL = {
  taskInstanceId: "2270057920872314670",
  workflowInstanceId: "-8242892283738776077",
  addedOn: "2024-11-19T10:56:25.713+00:00",
  addedBy: "-2317213366933091760",
  savedOn: "null",
  savedBy: "0",
  committedOn: "null",
  committedBy: "0",
  statusInId: "6555293821882597021",
  statusOutId: "0",
  tenantId: "7394915765950485780",
  nextTenantId: "0",
  nextTaskTypeId: "0",
  taskTypeId: "1436089270994646917",
  data: [
    988265, 0, 0, 0, 988262, 988260, 0, 988261, 988264, 988263, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  ],
  note: "null",
  renderingStyle: "Wizard",
  selectedTaskStatus: {
    tokenId: 0,
    id: "0",
    i18nName: "",
    startingTask: false,
    endingTask: false,
  },
  businessErrorMessage: "null",
  statuses: {
    "1": {
      tokenId: 988266,
      id: "-8262727858296587500",
      i18nName: "Submit",
      startingTask: true,
      endingTask: false,
    },
  },
  variables: {
    "33": {
      id: "33",
      tokenId: 0,
      i18nName: "resend_button",
      type: 8,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "OTP Verification",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "5936188268219494369",
      exitClassDataId: "988267",
      instanceId: "9801",
      textValue: null,
      numericValue: "0",
      displayOrder: 130,
      variableStyle: {
        bgColor: "#1F1F1F",
      },
    },
    "22": {
      id: "22",
      tokenId: 0,
      i18nName: "intro_label",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9790",
      textValue: `<h2 style="font-family: Inter; font-weight: 400; font-size: 16px; line-height: 23px; color:#1F1F1F">Get an instant micro-finance, starting from <b>SAR 2,000!</b> No paper work, fast approvals and flexible terms</h2>`,
      numericValue: "0",
      displayOrder: 20,
      variableStyle: {
        hideLabel: 1,
        isHtml: 1,
      },
    },
    "34": {
      id: "34",
      tokenId: 0,
      i18nName: "user_name",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "User Enrollment",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9802",
      textValue: null,
      numericValue: "0",
      displayOrder: 140,
      variableStyle: null,
    },
    "23": {
      id: "23",
      tokenId: 0,
      i18nName: "national_id_iqama_text",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9791",
      textValue: null,
      numericValue: "0",
      displayOrder: 30,
      variableStyle: {
        startIcon: "ID.svg",
      },
    },
    "35": {
      id: "35",
      tokenId: 0,
      i18nName: "name",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "User Enrollment",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9803",
      textValue: null,
      numericValue: "0",
      displayOrder: 150,
      variableStyle: null,
    },
    "24": {
      id: "24",
      tokenId: 0,
      i18nName: "saudi_mobile_number_text",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9792",
      textValue: null,
      numericValue: "0",
      displayOrder: 40,
      variableStyle: {
        startIcon: "SmartPhone.svg",
      },
    },
    "36": {
      id: "36",
      tokenId: 0,
      i18nName: "email",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "User Enrollment",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9804",
      textValue: null,
      numericValue: "0",
      displayOrder: 160,
      variableStyle: null,
    },
    "25": {
      id: "25",
      tokenId: 0,
      i18nName: "are_you_a_bab_customer_tick",
      type: 9,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 16,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9793",
      textValue: null,
      numericValue: "0",
      displayOrder: 50,
      variableStyle: null,
    },
    "37": {
      id: "37",
      tokenId: 0,
      i18nName: "password",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "User Enrollment",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9805",
      textValue: null,
      numericValue: "0",
      displayOrder: 170,
      variableStyle: null,
    },
    "26": {
      id: "26",
      tokenId: 0,
      i18nName: "t_an_c_tick",
      type: 9,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 16,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9794",
      textValue: null,
      numericValue: "0",
      displayOrder: 60,
      variableStyle: {
        isHtml: 1,
      },
    },
    "38": {
      id: "38",
      tokenId: 0,
      i18nName: "confirm_password",
      type: 1,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "User Enrollment",
      mimeType: null,
      jdbcType: 12,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9806",
      textValue: null,
      numericValue: "0",
      displayOrder: 180,
      variableStyle: null,
    },
    "27": {
      id: "27",
      tokenId: 0,
      i18nName: "marketing_tick",
      type: 9,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 16,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9795",
      textValue: null,
      numericValue: "0",
      displayOrder: 70,
      variableStyle: null,
    },
    "39": {
      id: "39",
      tokenId: 0,
      i18nName: "register_button",
      type: 8,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "User Enrollment",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "593460340710461666",
      exitClassDataId: "988268",
      instanceId: "9807",
      textValue: null,
      numericValue: "0",
      displayOrder: 190,
      variableStyle: null,
    },
    "28": {
      id: "28",
      tokenId: 0,
      i18nName: "button_apply",
      type: 8,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: -7,
      auditable: 0,
      exitClassId: "8646615755363102099",
      exitClassDataId: "988269",
      instanceId: "9796",
      textValue: null,
      numericValue: "0",
      displayOrder: 80,
      variableStyle: {
        bgColor: "#1F1F1F",
        endIcon: "RightBtnArrow.svg",
        isValidateBeforeClick: 1,
      },
    },
    "29": {
      id: "29",
      tokenId: 0,
      i18nName: "label_title",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "OTP Verification",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9797",
      textValue: `<div style="color:white; font-family: inter; font-weight:700;  font-size: 24px; line-height:31px; text-align: center;">A code was sent to your mobile number</div>`,
      numericValue: "0",
      displayOrder: 90,
      variableStyle: {
        isHtml: 1,
        hideLabel: 1,
      },
    },
    "30": {
      id: "30",
      tokenId: 0,
      i18nName: "label_sub_title",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "OTP Verification",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9798",
      textValue: `<div style="font-family: Inter; font-size: 16px; font-weight: 400;line-height: 23px;text-align: center; color: white; ">Please enter the code you received</div>`,
      numericValue: "0",
      displayOrder: 100,
      variableStyle: {
        isHtml: 1,
        hideLabel: 1,
      },
    },
    "31": {
      id: "31",
      tokenId: 0,
      i18nName: "otp",
      type: 2,
      comboListName: null,
      required: 1,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "OTP Verification",
      mimeType: null,
      jdbcType: 4,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9799",
      textValue: null,
      numericValue: "0",
      displayOrder: 110,
      variableStyle: null,
    },
    "32": {
      id: "32",
      tokenId: 0,
      i18nName: "label_desc",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "OTP Verification",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9800",
      textValue: `<div style="font-family: Inter; font-size: 14px; line-height: 23px;text-align: center; color: white; ">If you don't receive the mumber in 1:00 minute, click here</div>`,
      numericValue: "0",
      displayOrder: 120,
      variableStyle: {
        hideLabel: 1,
        isHtml: 1,
      },
    },
    "21": {
      id: "21",
      tokenId: 0,
      i18nName: "title_label",
      type: 1,
      comboListName: null,
      required: 0,
      hidden: 0,
      readOnly: 0,
      i18nGroupName: "Welcome",
      mimeType: null,
      jdbcType: 93,
      auditable: 0,
      exitClassId: "0",
      exitClassDataId: "0",
      instanceId: "9789",
      textValue: `<h1 style="font-family: Inter; font-weight: 700; font-size: 36px; line-height: 36px; color:#1F1F1F">Need <span style="color: #BD0000">more funds</span> over your current financing?</h1>`,
      numericValue: "0",
      displayOrder: 10,
      variableStyle: {
        hideLabel: 1,
        isHtml: 1,
      },
    },
  },
  variablesByName: {
    label_sub_title: "30",
    resend_button: "33",
    saudi_mobile_number_text: "24",
    t_an_c_tick: "26",
    label_title: "29",
    user_name: "34",
    marketing_tick: "27",
    otp: "31",
    register_button: "39",
    confirm_password: "38",
    button_go_next: "28",
    intro_label: "22",
    password: "37",
    are_you_a_bab_customer_tick: "25",
    name: "35",
    label_desc: "32",
    email: "36",
    national_id_iqama_text: "23",
    title_label: "21",
  },
};

export { yup };

export const JDBC_TYPE = {
  Button: -7,
  UploadDocument: -2,
  DecimalInput: 3,
  IntegerInput: 4,
  TextInput: 12,
  TextAreaInput: 2005,
  Checkbox: 16,
  URL: 70,
  DatePicker: 91,
  TimePicker: 92,
  Label: 93,
};

export const FORM_TYPE = {
  TAB: "Tab",
  WIZARD: "Wizard",
};

export const CONST_WORDS = {
  sessionTaskDetail: "CME_TASK_DETAIL",
};

export const ALLOWED_FILE_EXTENSION = ["pdf", "jpg", "png", "jpeg", "gif"];
